name: Test PR

on:
  pull_request:
    branches:
    - master

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: test and lint
      - run: yarn
      - run: yarn lint
      - run: yarn test
